### ISSUE TITLE
Error message in phone app

### ISSUE THREAD

**Issue by Gotty91** [saitamasahil/Lawnchair_Magisk#1]
![Screenshot_20230202-083036](https://user-images.githubusercontent.com/119973781/216265234-076691db-1f43-42c8-87c7-0846d5ee8011.png)

Android 13 stock gen patch
When I open the phone app this message appears 
Thanks

**Comment by saitamasahil** [comment]
To get rid of it simply download and install latest google dialer version from apk mirror which should **not have pixel-202** written in the name of the apk.
