### ISSUE TITLE
Lawnchair source changes?

### ISSUE THREAD

**Issue by osm0sis** [saitamasahil/Lawnchair_Magisk#11]
Hi! What changes were made to the Lawnchair apk source to support the latest Android for Recents? Please upload your Lawnchair repo.

**Comment by jacobchins** [comment]
Seconded, would love to see further support or assistance from others on this.

**Comment by rsnnn** [comment]
@saitamasahil so?

**Comment by osm0sis** [comment]
Nevermind, official Lawnchair has fixed their support now on the 13-dev branch. 👍
