### ISSUE TITLE
Just 2 small issues.

### ISSUE THREAD

**Issue by dongltron** [saitamasahil/Lawnchair_Magisk#2]
This is almost, almost perfect. My only two issues right now are to do with the Recents menu.

Issue 1 is there is a bug where swiping up on the app to dismiss it too quickly after the Recents menu gesture has been performed causes Lawnchair to scroll the app itself. It's quite quick but it happens to me often enough to be notable.

Issue 2 is I can't seem to select images or text in the Recents menu panel, from any app. There's no Select button to enable in the settings either so I'm presuming this is intentional?

Again, very small issues. This project is a lifesaver otherwise.

**Comment by Sergij-SApcPro** [comment]
The first issue happened to me with the stock trebuchet launcher. Maybe its a performance or lag issue.
