### ISSUE TITLE
Recent apps 

### ISSUE THREAD

**Issue by Karakalla1988** [saitamasahil/Lawnchair_Magisk#5]
I've installed your magisk module and it's great. I've a doubt about recent apps. There's a way to get working? If i scroll to get recent apps it appears "no recent apps" when I've open a lot of them. There's a fix?

**Comment by xenithorb** [comment]
I am also seeing this behavior   

20-20230323-NIGHTLY-fajita
lineage_fajita-userdebug 13 TQ2A.230305.008.C1 2dfcbf6ff1

**Comment by KrazyLurt** [comment]
Any fix for this ?

**Comment by xjl12** [comment]
It seems only happen in Android 13 QPR2 (android-13.0.0_r35). Maybe some framework API about get recent app list has changed.

**Comment by xjl12** [comment]
I have found a solution to this problem. On Android 13 QPR2, the `KEY_EXTRA_RECENT_TASKS` was abandoned, and we must use `KEY_EXTRA_SHELL_RECENT_TASKS` instead. So, the temporary solution is to decompile the current `a13.apk` and replace all `recent_tasks` to `extra_shell_recent_tasks` in smali codes.

Here is a properly working [module](https://github.com/xjl12/Lawnchair_Magisk/releases/download/Android_13_r35/lawnchair_in_a13_QPR2.zip).

**Comment by saitamasahil** [comment]
download latest version. thanks @xjl12

**Comment by KrazyDeinos** [comment]
Does it work with Googles security update for April?

**Comment by Egglestron** [comment]
Same problem with June 2023 security update, even with 1.3.1 version.

**Comment by pacjo** [comment]
> Same problem with June 2023 security update

Hmm, I'm on August now and it works fine. Pretty sure it was working on July too.
